### ISSUE TITLE
Pi4 v32 beta - Wrong aspect radio with bezel in auto with vertical games

### ISSUE THREAD

**Issue by chippettone** [batocera-linux/batocera-bezel#39]
I tested the V32 on PI4 .... Now no setting for the single game is no longer selectable. The vertical shooter are enlarged until the bezels are active. So if I want to have the correct screen report I have to have black bars because I can't use the bezels. By car they do not recognize the type of game and the default bezel is selected. Now the PI4 goes over the 1800s because otherwise the dash lags fearfully. Returning to the Bezel speech, activating Pixel Perfect, ne Core Provided You can have the correct video format with the bezels. If I want to change the bezel manually, acting on the entire core instead of the single game, the bezels are not needed now. So if I don't want the deformed game I have to have black bars on the sides. This was present in the V31 but now they have removed all the options and the bezels no longer go.

**Comment by lbrpdx** [comment]
I am not sure I understand your exact problem, could you precise what emulator (MAME? FBNeo?) and which rom as an example. However, as a general rule, you play a vertical shooter, you need to manually set `arcade_vertical_default` or `arcade_1980s_vertical` for this specific vertical rom. Otherwise, `defaut` for MAME will always set the bezel to the horizontal format, as the vast majority of games are meant to be played in horizontal mode.

**Comment by lbrpdx** [comment]
No response, and I can't understand why you say "setting for a single game is no longer selectable", as it is. Closing.
